### PR TITLE
fix HTTPS request for TOP

### PR DESCRIPTION
**Pull request by frogcjn**
fix HTTPS request for TOP

you can test it with https://eco.taobao.com/router/rest
or with sandbox environment https://gw.api.tbsandbox.com/router/rest

### CODE REVIEW

**Comment by frogcjn** [comment]
Another approach is remove `agent` property in `index.js`, let `request` to create the right agent for https protocol.

**Comment by bestmike007** [comment]
Why setting `strictSSL` to false?

**Comment by frogcjn** [comment]
Because if not set to false, request will make HTTPS request with strictSSL mode, which needs developer to provide  a CA bundle to verify the https request.

**Comment by frogcjn** [comment]
@bestmike007 
I'm sorry. I use a reverse proxy to test, so it needs turn off the strictSSL mode. I remove that line.

**Comment by bestmike007** [comment]
`strictSSL` - If `true`, requires SSL certificates be valid. Note: to use your own certificate authority, you need to specify an agent that was created with that CA as an option.

For most circumstances, we need the certificated to be valid in case of being intercepted. `eco.taobao.com` is using a valid certificate. However, it's okay to accept an option to bypass certificate check.

Please add tests for `https` requests. For now tests are not passing because the file uploading API for sandbox environment is not working. I'll check if it's affected by the recent adjustment that the picture uploading api is no longer free.

**Comment by frogcjn** [comment]
@bestmike007 I'm sorry. I use a reverse proxy to test, so it needs turn off the strictSSL mode. I have removed that line.

**Comment by bestmike007** [comment]
Good work!

**Comment by frogcjn** [comment]
Would you like to publish it?

**Comment by bestmike007** [comment]
Working on it...

**Comment by bestmike007** [comment]
I temporarily disabled file upload tests. It's now on npm with version 1.0.6

**Pull request merged**
